### ISSUE TITLE
Project Setup

### ISSUE THREAD

**Issue by bmaximilian** [bmaximilian/curion-address-service#1]
### Tasks
- [x] Setup webserver and API containers
- [x] Setup MSSQL database container
- [x] Initialize blank Laravel
- [x] Initialize blank Angular
- [x] Github actions to link the code and run the tests
