### ISSUE TITLE
Initialize Address functionality

### ISSUE THREAD

**Issue by bmaximilian** [bmaximilian/curion-address-service#2]
### Tasks
- [x] Add migration for addresses table
- [x] Add models, controller and services to fetch addresses
- [x] Add route to get all addresses
- [x] Add route to get one address
- [x] Seed addresses
