### ISSUE TITLE
Setup frame of angular application

### ISSUE THREAD

**Issue by bmaximilian** [bmaximilian/curion-address-service#4]
### Tasks
- [x] Setup root components
- [x] Setup component library ([Material UI](https://material.angular.io/))
- [x] Setup state management ([Redux](https://redux.js.org/))
